// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ddatdt12/kapo-play-ws-server/internal/protocols/http"
)

// Injectors from wire.go:

func InitHttpProtocol() *http.HttpImpl {
	httpImpl := http.NewHttpProtocol()
	return httpImpl
}
